<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'brand_id' => 1,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2017/05/02/85/36/57/8/item_XL_8536578_31279073.jpg',
                'manufacturer_id' => 4,
                'stock' => 18,
                'minimum_stock' => 6,
                'price' => 333.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:40:14',
                'updated_at' => '2019-11-10 15:40:14',
            ),
            1 => 
            array (
                'id' => 2,
                'brand_id' => 4,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2016/05/08/10/70/00/83/item_XL_10700083_14220480.jpg',
                'manufacturer_id' => 3,
                'stock' => 23,
                'minimum_stock' => 3,
                'price' => 295.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 5,
                'created_at' => '2019-11-10 15:40:16',
                'updated_at' => '2019-11-10 15:40:16',
            ),
            2 => 
            array (
                'id' => 3,
                'brand_id' => 4,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2017/10/26/75/86/60/7/item_XL_7586607_56749309.jpg',
                'manufacturer_id' => 2,
                'stock' => 2,
                'minimum_stock' => 7,
                'price' => 995.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 1,
                'created_at' => '2019-11-10 15:40:18',
                'updated_at' => '2019-11-10 15:40:18',
            ),
            3 => 
            array (
                'id' => 4,
                'brand_id' => 4,
                'thumbnail' => '',
                'manufacturer_id' => 5,
                'stock' => 12,
                'minimum_stock' => 4,
                'price' => 1399.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 2,
                'created_at' => '2019-11-10 15:40:21',
                'updated_at' => '2019-11-10 15:40:21',
            ),
            4 => 
            array (
                'id' => 5,
                'brand_id' => 5,
                'thumbnail' => 'https://cf4.s3.souqcdn.com/item/2015/11/19/95/68/16/7/item_XL_9568167_10883856.jpg',
                'manufacturer_id' => 2,
                'stock' => 25,
                'minimum_stock' => 7,
                'price' => 138.5,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 4,
                'created_at' => '2019-11-10 15:40:24',
                'updated_at' => '2019-11-10 15:40:24',
            ),
            5 => 
            array (
                'id' => 6,
                'brand_id' => 3,
                'thumbnail' => 'https://cf2.s3.souqcdn.com/item/2018/01/24/30/30/57/30/item_XL_30305730_94164650.jpg',
                'manufacturer_id' => 1,
                'stock' => 14,
                'minimum_stock' => 3,
                'price' => 169.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 4,
                'created_at' => '2019-11-10 15:40:27',
                'updated_at' => '2019-11-10 15:40:27',
            ),
            6 => 
            array (
                'id' => 7,
                'brand_id' => 5,
                'thumbnail' => '',
                'manufacturer_id' => 1,
                'stock' => 20,
                'minimum_stock' => 5,
                'price' => 94.8,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 2,
                'created_at' => '2019-11-10 15:40:30',
                'updated_at' => '2019-11-10 15:40:30',
            ),
            7 => 
            array (
                'id' => 8,
                'brand_id' => 3,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2017/09/05/23/92/01/63/item_XL_23920163_34930873.jpg',
                'manufacturer_id' => 1,
                'stock' => 15,
                'minimum_stock' => 4,
                'price' => 1799.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 7,
                'created_at' => '2019-11-10 15:40:33',
                'updated_at' => '2019-11-10 15:40:33',
            ),
            8 => 
            array (
                'id' => 9,
                'brand_id' => 3,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2016/03/08/10/15/98/69/item_XL_10159869_12832160.jpg',
                'manufacturer_id' => 1,
                'stock' => 21,
                'minimum_stock' => 5,
                'price' => 89.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 5,
                'created_at' => '2019-11-10 15:40:35',
                'updated_at' => '2019-11-10 15:40:35',
            ),
            9 => 
            array (
                'id' => 10,
                'brand_id' => 3,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2015/06/24/85/32/02/2/item_XL_8532022_8380988.jpg',
                'manufacturer_id' => 5,
                'stock' => 15,
                'minimum_stock' => 6,
                'price' => 375.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 4,
                'created_at' => '2019-11-10 15:40:38',
                'updated_at' => '2019-11-10 15:40:38',
            ),
            10 => 
            array (
                'id' => 11,
                'brand_id' => 4,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2015/10/30/94/08/15/4/item_XL_9408154_10398843.jpg',
                'manufacturer_id' => 2,
                'stock' => 22,
                'minimum_stock' => 6,
                'price' => 142.5,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 1,
                'created_at' => '2019-11-10 15:40:41',
                'updated_at' => '2019-11-10 15:40:41',
            ),
            11 => 
            array (
                'id' => 12,
                'brand_id' => 2,
                'thumbnail' => '',
                'manufacturer_id' => 2,
                'stock' => 5,
                'minimum_stock' => 3,
                'price' => 57.9,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 5,
                'created_at' => '2019-11-10 15:40:44',
                'updated_at' => '2019-11-10 15:40:44',
            ),
            12 => 
            array (
                'id' => 13,
                'brand_id' => 2,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2017/10/01/99/52/70/2/item_XL_9952702_35908678.jpg',
                'manufacturer_id' => 1,
                'stock' => 2,
                'minimum_stock' => 6,
                'price' => 100.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 5,
                'created_at' => '2019-11-10 15:40:46',
                'updated_at' => '2019-11-10 15:40:46',
            ),
            13 => 
            array (
                'id' => 14,
                'brand_id' => 4,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2019/05/21/27/45/40/88/item_XL_27454088_2d37f6f4fb8c5.jpg',
                'manufacturer_id' => 3,
                'stock' => 12,
                'minimum_stock' => 1,
                'price' => 195.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 7,
                'created_at' => '2019-11-10 15:40:49',
                'updated_at' => '2019-11-10 15:40:49',
            ),
            14 => 
            array (
                'id' => 15,
                'brand_id' => 1,
                'thumbnail' => '',
                'manufacturer_id' => 5,
                'stock' => 3,
                'minimum_stock' => 4,
                'price' => 219.95,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:40:51',
                'updated_at' => '2019-11-10 15:40:51',
            ),
            15 => 
            array (
                'id' => 16,
                'brand_id' => 2,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2014/09/25/73/30/25/1/item_XL_7330251_5701244.jpg',
                'manufacturer_id' => 5,
                'stock' => 10,
                'minimum_stock' => 7,
                'price' => 23.33,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 2,
                'created_at' => '2019-11-10 15:40:55',
                'updated_at' => '2019-11-10 15:40:55',
            ),
            16 => 
            array (
                'id' => 17,
                'brand_id' => 3,
                'thumbnail' => '',
                'manufacturer_id' => 1,
                'stock' => 16,
                'minimum_stock' => 1,
                'price' => 199.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 1,
                'created_at' => '2019-11-10 15:40:58',
                'updated_at' => '2019-11-10 15:40:58',
            ),
            17 => 
            array (
                'id' => 18,
                'brand_id' => 4,
                'thumbnail' => '',
                'manufacturer_id' => 1,
                'stock' => 26,
                'minimum_stock' => 5,
                'price' => 72.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 7,
                'created_at' => '2019-11-10 15:41:01',
                'updated_at' => '2019-11-10 15:41:01',
            ),
            18 => 
            array (
                'id' => 19,
                'brand_id' => 4,
                'thumbnail' => '',
                'manufacturer_id' => 5,
                'stock' => 9,
                'minimum_stock' => 3,
                'price' => 699.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:41:03',
                'updated_at' => '2019-11-10 15:41:03',
            ),
            19 => 
            array (
                'id' => 20,
                'brand_id' => 4,
                'thumbnail' => 'https://cf2.s3.souqcdn.com/item/2015/02/15/78/57/45/3/item_XL_7857453_6919286.jpg',
                'manufacturer_id' => 5,
                'stock' => 9,
                'minimum_stock' => 5,
                'price' => 599.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 7,
                'created_at' => '2019-11-10 15:41:06',
                'updated_at' => '2019-11-10 15:41:06',
            ),
            20 => 
            array (
                'id' => 21,
                'brand_id' => 1,
                'thumbnail' => 'https://cf1.s3.souqcdn.com/item/2018/02/14/30/67/91/11/item_XL_30679111_110754187.jpg',
                'manufacturer_id' => 5,
                'stock' => 30,
                'minimum_stock' => 1,
                'price' => 4702.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 2,
                'created_at' => '2019-11-10 15:41:09',
                'updated_at' => '2019-11-10 15:41:09',
            ),
            21 => 
            array (
                'id' => 22,
                'brand_id' => 5,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2019/03/10/23/86/59/09/item_XL_23865909_085df458b7822.jpg',
                'manufacturer_id' => 5,
                'stock' => 4,
                'minimum_stock' => 2,
                'price' => 39.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:41:11',
                'updated_at' => '2019-11-10 15:41:11',
            ),
            22 => 
            array (
                'id' => 23,
                'brand_id' => 5,
                'thumbnail' => '',
                'manufacturer_id' => 2,
                'stock' => 8,
                'minimum_stock' => 6,
                'price' => 105.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 3,
                'created_at' => '2019-11-10 15:41:13',
                'updated_at' => '2019-11-10 15:41:13',
            ),
            23 => 
            array (
                'id' => 24,
                'brand_id' => 4,
                'thumbnail' => '',
                'manufacturer_id' => 3,
                'stock' => 6,
                'minimum_stock' => 2,
                'price' => 1500.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:41:16',
                'updated_at' => '2019-11-10 15:41:16',
            ),
            24 => 
            array (
                'id' => 25,
                'brand_id' => 3,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2016/03/08/10/15/98/62/item_XL_10159862_12832102.jpg',
                'manufacturer_id' => 5,
                'stock' => 24,
                'minimum_stock' => 6,
                'price' => 89.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 1,
                'created_at' => '2019-11-10 15:41:19',
                'updated_at' => '2019-11-10 15:41:19',
            ),
            25 => 
            array (
                'id' => 26,
                'brand_id' => 3,
                'thumbnail' => 'https://cf1.s3.souqcdn.com/item/2017/01/12/11/78/21/20/item_XL_11782120_18404018.jpg',
                'manufacturer_id' => 4,
                'stock' => 26,
                'minimum_stock' => 3,
                'price' => 2999.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:41:21',
                'updated_at' => '2019-11-10 15:41:21',
            ),
            26 => 
            array (
                'id' => 27,
                'brand_id' => 1,
                'thumbnail' => 'https://cf2.s3.souqcdn.com/item/2017/08/16/23/82/85/75/item_XL_23828575_34516049.jpg',
                'manufacturer_id' => 4,
                'stock' => 11,
                'minimum_stock' => 1,
                'price' => 649.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 1,
                'created_at' => '2019-11-10 15:41:24',
                'updated_at' => '2019-11-10 15:41:24',
            ),
            27 => 
            array (
                'id' => 28,
                'brand_id' => 5,
                'thumbnail' => '',
                'manufacturer_id' => 5,
                'stock' => 17,
                'minimum_stock' => 3,
                'price' => 4296.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:41:26',
                'updated_at' => '2019-11-10 15:41:26',
            ),
            28 => 
            array (
                'id' => 29,
                'brand_id' => 5,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2017/05/21/22/83/56/04/item_XL_22835604_31850878.jpg',
                'manufacturer_id' => 1,
                'stock' => 26,
                'minimum_stock' => 7,
                'price' => 2222.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 7,
                'created_at' => '2019-11-10 15:41:28',
                'updated_at' => '2019-11-10 15:41:28',
            ),
            29 => 
            array (
                'id' => 30,
                'brand_id' => 4,
                'thumbnail' => '',
                'manufacturer_id' => 5,
                'stock' => 13,
                'minimum_stock' => 7,
                'price' => 910.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 4,
                'created_at' => '2019-11-10 15:41:31',
                'updated_at' => '2019-11-10 15:41:31',
            ),
            30 => 
            array (
                'id' => 31,
                'brand_id' => 2,
                'thumbnail' => 'https://cf1.s3.souqcdn.com/item/2018/02/06/30/56/14/83/item_XL_30561483_108052699.jpg',
                'manufacturer_id' => 2,
                'stock' => 26,
                'minimum_stock' => 5,
                'price' => 1799.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 5,
                'created_at' => '2019-11-10 15:41:34',
                'updated_at' => '2019-11-10 15:41:34',
            ),
            31 => 
            array (
                'id' => 32,
                'brand_id' => 2,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2017/08/02/23/66/69/35/item_XL_23666935_34008099.jpg',
                'manufacturer_id' => 4,
                'stock' => 11,
                'minimum_stock' => 7,
                'price' => 2298.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 3,
                'created_at' => '2019-11-10 15:41:36',
                'updated_at' => '2019-11-10 15:41:36',
            ),
            32 => 
            array (
                'id' => 33,
                'brand_id' => 2,
                'thumbnail' => '',
                'manufacturer_id' => 2,
                'stock' => 29,
                'minimum_stock' => 7,
                'price' => 1399.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 6,
                'created_at' => '2019-11-10 15:41:38',
                'updated_at' => '2019-11-10 15:41:38',
            ),
            33 => 
            array (
                'id' => 34,
                'brand_id' => 4,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2016/05/08/10/70/00/83/item_XL_10700083_14220480.jpg',
                'manufacturer_id' => 2,
                'stock' => 7,
                'minimum_stock' => 4,
                'price' => 295.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 3,
                'created_at' => '2019-11-10 15:41:41',
                'updated_at' => '2019-11-10 15:41:41',
            ),
            34 => 
            array (
                'id' => 35,
                'brand_id' => 5,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2017/12/05/28/77/87/45/item_XL_28778745_80910350.jpg',
                'manufacturer_id' => 4,
                'stock' => 25,
                'minimum_stock' => 7,
                'price' => 35.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 2,
                'created_at' => '2019-11-10 15:41:43',
                'updated_at' => '2019-11-10 15:41:43',
            ),
            35 => 
            array (
                'id' => 36,
                'brand_id' => 2,
                'thumbnail' => 'https://cf5.s3.souqcdn.com/item/2015/06/24/85/32/02/2/item_XL_8532022_8380988.jpg',
                'manufacturer_id' => 1,
                'stock' => 30,
                'minimum_stock' => 6,
                'price' => 375.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 1,
                'created_at' => '2019-11-10 15:41:45',
                'updated_at' => '2019-11-10 15:41:45',
            ),
            36 => 
            array (
                'id' => 37,
                'brand_id' => 2,
                'thumbnail' => 'https://cf1.s3.souqcdn.com/item/2018/09/25/67/25/38/2/item_XL_6725382_151540265.jpg',
                'manufacturer_id' => 4,
                'stock' => 13,
                'minimum_stock' => 7,
                'price' => 345.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 2,
                'created_at' => '2019-11-10 15:41:48',
                'updated_at' => '2019-11-10 15:41:48',
            ),
            37 => 
            array (
                'id' => 38,
                'brand_id' => 5,
                'thumbnail' => 'https://cf3.s3.souqcdn.com/item/2018/02/12/30/65/59/59/item_XL_30655959_110485915.jpg',
                'manufacturer_id' => 2,
                'stock' => 25,
                'minimum_stock' => 6,
                'price' => 60.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 2,
                'created_at' => '2019-11-10 15:41:50',
                'updated_at' => '2019-11-10 15:41:50',
            ),
            38 => 
            array (
                'id' => 39,
                'brand_id' => 1,
                'thumbnail' => '',
                'manufacturer_id' => 5,
                'stock' => 13,
                'minimum_stock' => 7,
                'price' => 4.0,
                'is_active' => 1,
                'up_selling' => 1,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 1,
                'created_at' => '2019-11-10 15:41:53',
                'updated_at' => '2019-11-10 15:41:53',
            ),
            39 => 
            array (
                'id' => 41,
                'brand_id' => 4,
                'thumbnail' => NULL,
                'manufacturer_id' => 1,
                'stock' => 1000,
                'minimum_stock' => 50,
                'price' => 700.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 0,
                'created_at' => '2019-11-11 10:32:46',
                'updated_at' => '2019-11-11 12:42:00',
            ),
            40 => 
            array (
                'id' => 42,
                'brand_id' => 9,
                'thumbnail' => 'ltztouvg8dlb2uer.jpg',
                'manufacturer_id' => 71,
                'stock' => 800,
                'minimum_stock' => 40,
                'price' => 7000.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 1,
                'before_price' => 8000.0,
                'return_allowed' => 1,
                'return_duration' => 7,
                'created_at' => '2019-11-11 10:38:43',
                'updated_at' => '2019-11-11 10:38:43',
            ),
            41 => 
            array (
                'id' => 43,
                'brand_id' => 9,
                'thumbnail' => NULL,
                'manufacturer_id' => 71,
                'stock' => 1000,
                'minimum_stock' => 20,
                'price' => 7000.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 7,
                'created_at' => '2019-11-11 13:10:54',
                'updated_at' => '2019-11-13 13:24:18',
            ),
            42 => 
            array (
                'id' => 44,
                'brand_id' => 8,
                'thumbnail' => NULL,
                'manufacturer_id' => 71,
                'stock' => 400,
                'minimum_stock' => 20,
                'price' => 150.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 0,
                'created_at' => '2019-11-11 13:30:19',
                'updated_at' => '2019-11-13 13:22:24',
            ),
            43 => 
            array (
                'id' => 45,
                'brand_id' => 11,
                'thumbnail' => NULL,
                'manufacturer_id' => 71,
                'stock' => 2000,
                'minimum_stock' => 100,
                'price' => 7000.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 0,
                'created_at' => '2019-11-12 11:33:58',
                'updated_at' => '2019-11-13 09:38:31',
            ),
            44 => 
            array (
                'id' => 46,
                'brand_id' => 5,
                'thumbnail' => NULL,
                'manufacturer_id' => 71,
                'stock' => 2000,
                'minimum_stock' => 100,
                'price' => 1200.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 0,
                'return_duration' => 0,
                'created_at' => '2019-11-12 12:28:38',
                'updated_at' => '2019-11-12 12:30:35',
            ),
            45 => 
            array (
                'id' => 47,
                'brand_id' => 11,
                'thumbnail' => NULL,
                'manufacturer_id' => 71,
                'stock' => 1200,
                'minimum_stock' => 100,
                'price' => 7700.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 1,
                'before_price' => 8200.0,
                'return_allowed' => 1,
                'return_duration' => 7,
                'created_at' => '2019-11-13 09:59:06',
                'updated_at' => '2019-11-13 12:02:50',
            ),
            46 => 
            array (
                'id' => 50,
                'brand_id' => 4,
                'thumbnail' => 'mxriioazwlzwi6cp.jpg',
                'manufacturer_id' => 71,
                'stock' => 1300,
                'minimum_stock' => 25,
                'price' => 1500.0,
                'is_active' => 1,
                'up_selling' => 0,
                'on_sale' => 0,
                'before_price' => 0.0,
                'return_allowed' => 1,
                'return_duration' => 14,
                'created_at' => '2019-11-13 13:14:03',
                'updated_at' => '2019-11-13 13:14:03',
            ),
        ));
        
        
    }
}